version: '3.8'

services:
  # FastAPI backend
  backend:
    build: ./backend
    container_name: chhoti-pdf-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  # Vite dev server (development only)
  frontend:
    build: ./frontend
    container_name: chhoti-pdf-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Production web server (builds frontend and serves with Nginx, proxies /api)
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: chhoti-pdf-web
    ports:
      - "80:80"
    depends_on:
      - backend
    profiles:
      - production
